### ISSUE TITLE
Fails a test in t/radial.t

### ISSUE THREAD

**Issue by moritz** [perlpilot/p6-Math-Trig#4]
```
moritz@hack:~/p6/p6-Math-Trig$ PERL6LIB=lib prove -e perl6-m t/
t/01-basic.t ......... ok     
t/02-default.t ....... ok   
t/03-radial.t ........ 1/30 
# Failed test at t/03-radial.t line 49
# expected: 0
# got:      8.65956056235493e-17
# Looks like you failed 1 test of 30
t/03-radial.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/30 subtests 
t/04-great-circle.t .. ok     

Test Summary Report
-------------------
t/03-radial.t      (Wstat: 256 Tests: 30 Failed: 1)
  Failed test:  24
  Non-zero exit status: 1
Files=4, Tests=89,  5 wallclock secs ( 0.03 usr  0.01 sys +  4.82 cusr  0.19 csys =  5.05 CPU)
Result: FAIL
```

The failing test does an `is-approx($some-number, 0)`, which might be not
handled well by current is-approx.

**Comment by perlpilot** [comment]
Doesn't fail for me ...
> /home/duff/repo/p6-Math-Trig [master u=]
> ➤ prove -e 'perl6 -Ilib' t
> t/01-basic.t ......... ok     
> t/02-default.t ....... ok   
> t/03-radial.t ........ ok     
> t/04-great-circle.t .. ok     
> All tests successful.
> Files=4, Tests=89,  4 wallclock secs ( 0.05 usr  0.01 sys +  3.41 cusr  0.21 csys =  3.68 CPU)
> Result: PASS

So ... closing.
